### ISSUE TITLE
Good job!

### ISSUE THREAD

**Issue by Arturszott** [sarink/react-file-drop#10]
The plugin works great. I tried to figure it out how to detect one time only event when I drag files and your solution with counting dragenters was the best. 

Just tell me if you would like me to write couple tests in this repo!

Cheers.

**Comment by sarink** [comment]
Would love some tests! If you can, please try to use the most barebones-no-configuration architecture possible, this project is so simple (literally one file) and I want to keep it lean.
Thanks!
