### ISSUE TITLE
File uploading gets fired 2 times

### ISSUE THREAD

**Issue by vladimir-konnov** [sarink/react-file-drop#21]
Please look at the line below
https://github.com/sarink/react-file-drop/blob/24f306cdbde6d1d5e85c67cd5b3e615dff37aa49/FileDrop.js#L108
The `_handleDrop` handler gets fired two times when dropping to target:
1. `onDrop` event gets fired on `div.file-drop` element, so its handler `_handleDrop` is called
2. `_handleFrameDrop` gets fired on frames' `drop` event (https://github.com/sarink/react-file-drop/blob/24f306cdbde6d1d5e85c67cd5b3e615dff37aa49/FileDrop.js#L170) which calls `_handleDrop` once again.

And this `_handleDrop` handler invokes `this.props.onDrop` handler which usually uploads files to the server, so any file gets uploaded to the backend 2 times.

The general idea is: you should not call a `drop-to-target` handler when drop to a `frame-not-target` is performed. I think removing line https://github.com/sarink/react-file-drop/blob/24f306cdbde6d1d5e85c67cd5b3e615dff37aa49/FileDrop.js#L108 is a good idea, because `_handleFrameDrop` (up to my opinion) represents the drop to a `frame-not-target` area, especially `if (!this.state.draggingOverTarget)` part. I think there shouldn't be `else` branch (or code except inside this `if` statement) because it may lead to the situations like I described.

So as a workaround I will stick to version `0.1.8` until it is fixed.

P.S. I understand that you've made this change because of https://github.com/sarink/react-file-drop/pull/17. I don't know the use case behind this PR, but I assume that the solution should be other than this one.

**Comment by vladimir-konnov** [comment]
Also maybe https://github.com/sarink/react-file-drop/issues/20 is related to this problem as well.

**Comment by racingrebel** [comment]
@vladimir-konnov Thank you, I've been having this issue as well.

**Comment by sarink** [comment]
Please use the `disableDoubleDrop` prop in the meantime
