### ISSUE TITLE
how to make the whole screen dropable ?

### ISSUE THREAD

**Issue by naveenanilabs** [sarink/react-file-drop#28]
is there any method to make the whole page dropable.
<FileDrop
            frame={document}
            onDrop={props.handleFileDrop}
            onFrameDrop={props.handleFileDrop}
            className="dragBrowse"
            id="Attachments"
          >
no example containing frame as HTMLElement

**Comment by sarink** [comment]
Hi @naveenanilabs, you can render the component wherever you like? Render it over your top-level component if you want

**Comment by naveenanilabs** [comment]
i can't render my component over top-level component. Is there anyway i can achieve this in my child component itself?

**Comment by sarink** [comment]
@naveenanilabs have you looked into how portals work in react? https://reactjs.org/docs/portals.html you could render a portal and give it full width/height
