### ISSUE TITLE
Files with extension app show wrong size

### ISSUE THREAD

**Issue by whiteadi** [sarink/react-file-drop#29]
First: nice module I found it useful for using whole document as target without changing the style of the app. 

The problem I found is, as you can try it in your demo, if you drag and drop a file with extension app 

(I use mac) the size is reported as 96.

Regards,
Adrian

**Comment by sarink** [comment]
@whiteadi I'm not seeing the behavior you describe, are you saying that _all_ files without an extension are reported as `size: 96`? 
Here are my results when dragging the same png file, with the extension and without the extension
```
{
  lastModified: 1529277456128
  lastModifiedDate: Sun Jun 17 2018 18:17:36 GMT-0500 (Central Daylight Time) {}
  name: "clover"
  size: 19813
  type: ""
  webkitRelativePath: ""
}
```
```
{
  lastModified: 1529277456128
  lastModifiedDate: Sun Jun 17 2018 18:17:36 GMT-0500 (Central Daylight Time) {}
  name: "clover.png"
  size: 19813
  type: "image/png"
  webkitRelativePath: ""
}
```

**Comment by whiteadi** [comment]
Hi,

I tested it with this component: [react-dropzone](https://github.com/react-dropzone/react-dropzone) and there it works with app type files, shows the good 

size, but even your demo: [http://sarink.github.io/react-file-drop/dist/Demo/](http://sarink.github.io/react-file-drop/dist/Demo/),

i you tested on mac and chrome and it shows 96, but please don't change the extension because 

somehow that is not giving the same result...

[Here it is](https://www.dropbox.com/s/mizptyljpokih11/Screenshot%202018-06-26%2009.49.25.png?dl=0)

**Comment by whiteadi** [comment]
<img width="1660" alt="screenshot 2018-06-26 09 49 25" src="https://user-images.githubusercontent.com/4496789/41897121-b9408646-7926-11e8-93ac-e11acb8a8de1.png">

**Comment by sarink** [comment]
Hmm, as you can see [here](https://github.com/sarink/react-file-drop/blob/master/src/FileDrop/FileDrop.tsx#L128) we don't do anything with the files, they come directly from `event.dataTransfer.files`

**Comment by whiteadi** [comment]
Indeed I see it, funny is that I cannot find anyone else having this problem, I google app type files mac 96 drop file..., nothing.

The other module that does not have this problem is using this method:

```
export function getDataTransferItems(event) {
  var dataTransferItemsList = [];
  if (event.dataTransfer) {
    var dt = event.dataTransfer;
    if (dt.files && dt.files.length) {
      dataTransferItemsList = dt.files;
    } else if (dt.items && dt.items.length) {
      // During the drag even the dataTransfer.files is null
      // but Chrome implements some drag store, which is accesible via dataTransfer.items
      dataTransferItemsList = dt.items;
    }
  } else if (event.target && event.target.files) {
    dataTransferItemsList = event.target.files;
  }
  // Convert from DataTransferItemsList to the native Array
  
 return Array.prototype.slice.call(dataTransferItemsList);
}
```
and it is in this section that is handled:

```
else if (event.target && event.target.files) {
    dataTransferItemsList = event.target.files;
  }
```
and if so the files from event.target.files show correct size.

![screenshot 2018-07-05 15 06 07](https://user-images.githubusercontent.com/4496789/42324978-250e50ac-8065-11e8-9981-85f570126a08.png)
