### ISSUE TITLE
I cannot reopen so:

### ISSUE THREAD

**Issue by whiteadi** [sarink/react-file-drop#30]
Hi,

this is about the closed one -> 

> if you drag and drop a file with extension app
> 
> (at least on mac) the size is reported as 96

:

I tested it with this component: [react-dropzone](https://github.com/react-dropzone/react-dropzone) and there it works with **app** type files, shows the good 

size, but even your demo: [http://sarink.github.io/react-file-drop/dist/Demo/](http://sarink.github.io/react-file-drop/dist/Demo/),

i you tested on **mac** and **chrome** and it shows 96, but please don't change the extension because 

somehow that is not giving the same result...

[Here it is](https://www.dropbox.com/s/mizptyljpokih11/Screenshot%202018-06-26%2009.49.25.png?dl=0)

I used iTerm.app as file to drag and drop: [here](https://www.iterm2.com/downloads.html)

**Comment by sarink** [comment]
@whiteadi did you try this yet? https://github.com/sarink/react-file-drop/issues/29#issuecomment-401121087

**Comment by whiteadi** [comment]
I see is the browser indeed, if you use this  with chrome on mac: https://jsfiddle.net/user2314737/mnfztctt/

it behaves like that also, so it is chrome (on mac)

so I submitted an issue at google :)

You can close this issue, thanks for the patience :)
