### ISSUE TITLE
dropping folders

### ISSUE THREAD

**Issue by paddotk** [sarink/react-file-drop#32]
Hi,

Dropping folders onto the dropzone doesn't work (and that's fine by me). However, to avoid the whole page from breaking, I'd like to be able to handle this somehow. I've looked into the `file` and `event` objects, but couldn't find anything that indicates whether the thing that was dropped is a folder or (a) file(s).
Default file events from `<input type="file"/>` elements have the properties `isDirectory: true/false` and `isFile: true/false`. Could you add this to the events of the dropped items? That would be really useful and appreciated :)

Great library otherwise!!

**Comment by sarink** [comment]
Dropping folders works in the demo app? Can you elaborate on the problem/what breaks a little bit more? Also, the second argument to `onDrop` is the unmodified drop `event`, does it contain what you need?

**Comment by paddotk** [comment]
@sarink Sorry, I was half right; it doesn't break the page (that was just my own validation :p) but gives no actual data of the files within the folder. It looks like the file-drop component assumes it's a file, rather than an array of files. Therefore I can't really do anything with it.

In the `event` arg I can't find anything that says whether it's a file or a directory. Maybe it's in there somewhere but not in an easy-to-find place, in which case I'd like to know where I can find such a key.

Thanks!

**Comment by sarink** [comment]
https://stackoverflow.com/questions/3590058/does-html5-allow-drag-drop-upload-of-folders-or-a-folder-tree does `event.dataTransfer.items` work?

**Comment by paddotk** [comment]
`event.dataTransfer.items` contains `{ kind: "file", type: "" }` when dropping a folder. Nothing else in the `event.dataTransfer` object seems to contain anything useful.

**Comment by sarink** [comment]
Did you do `item.webkitGetAsEntry()`? That seems to be the magic, at least according to https://developers.google.com/web/updates/2012/07/Drag-and-drop-a-folder-onto-Chrome-now-available

**Comment by sarink** [comment]
Update: tried out `event.dataTransfer.items[0].webkitGetAsEntry()` in the demo and it gave me `DirectoryEntry {isFile: false, isDirectory: true, name: "tv", fullPath: "/tv", filesystem: DOMFileSystem}` - which I believe is exactly what you wanted. Closing!

**Comment by paddotk** [comment]
@sarink Terrific, thanks!! :D
