### ISSUE TITLE
yarn test failure

### ISSUE THREAD

**Issue by sudhakarnraju** [sarink/react-file-drop#34]
Building reactjs app. However after including react-file-drop library, getting the below error for yarn test (jest framework). However yarn build, start etc works good and no issues found in runtime.
**Error:**
/web/node_modules/react-
file-drop/dist/FileDrop/FileDrop.js:23
    import React from 'react'
    ^^^^^^
    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:289:17)

**This is my Package.json (removed few entries not relevant to this)**
{
  "name": "xxxxxxxx",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@types/react": "^16.4.4",
    "prop-types": "^15.6.2",
    "react": "^16.4.1",
    "react-file-drop": "^0.2.6",
    "react-scripts": "1.1.4",
    "webpack": "^3.12.0"
  },
  "scripts": {
    "test": "react-scripts test --env=jsdom",
  },
  "jest": {
    "coverageReporters": [
      "json",
      "text",
      "lcov",
      "cobertura"
    ]
  }
}

**Comment by sarink** [comment]
It looks like jest can't understand the `import React` line - this is likely due to a local configuration error.
