### ISSUE TITLE
[Styling] Cannot style when using css-loader localIdentName

### ISSUE THREAD

**Issue by racingrebel** [sarink/react-file-drop#35]
A handful projects nowadays are making their css classes unique to avoid conflicts if their project is used in another bigger project.

Using the css-loader localIdentName is one way to solve that problem for an entire project that imports SCSS files. The classes for react-file-drop are hard coded into the module. If I were to define '.fileDrop', the css-loader might be configured to change the name to '.fileDrop_a24f2' for example. react-file-drop will not recognize this class and ignore it. 

If there were props for supplying custom classnames like:
targetClassName
draggingOverFrameClassName
draggingOverTargetClassName

That would solve this problem.
What do you think?
I can create a PR if you would like.

**Comment by sarink** [comment]
Great idea! Should be backwards-compatible if the current hard coded classnames are specified as the defaults. Welcoming this PR with open arms 🤗

**Comment by racingrebel** [comment]
Of course! Be on the look out in the near future :man_factory_worker:
