### ISSUE TITLE
Jest issue

### ISSUE THREAD

**Issue by paddotk** [sarink/react-file-drop#37]
Hi,

We use Jest for our unit testing. When I try to test a component which imports react-file-drop, Jest throws an error coming from `/node_modules/react-file-drop/dist/FileDrop/FileDrop.js:11`:
```
    import PropTypes from 'prop-types';
    ^^^^^^
    SyntaxError: Unexpected token import
```
I've tried installing proptypes with npm, but to no avail. Is there any way to fix or circumvent this?
P.s. I don't know if it has anything to do with it, but we use Typescript for type checking in our application.

**Comment by sarink** [comment]
`Unexpected token import` tells me that the problem is with your configuration not understanding ES6 modules. This is not a `react-file-drop` problem.

**Comment by sarink** [comment]
Have a look here https://github.com/facebook/jest/issues/2081
