### ISSUE TITLE
dist/FileDrop.js contains ES6 code

### ISSUE THREAD

**Issue by stevebaxter** [sarink/react-file-drop#39]
This is a great little library but we can't use it because for some reason FileDrop.js contains what looks like ES6 code, even though the target is set to ES5:

https://github.com/sarink/react-file-drop/blob/master/dist/FileDrop/FileDrop.js#L11

This means that it won't compile for Jest Storybook tests.

**Comment by sarink** [comment]
Hey @stevebaxter, what sort of module system are you using? Of course this library is going to require react, are you expecting a `require` syntax instead of `import`, or, what would work for you?

**Comment by stevebaxter** [comment]
We're using Typescript, Babel and Webpack. We're compiling to ES5 at the moment because of Jest.

The problem is that it looks like your tsconfig.json is set up to generate ES5 code:

https://github.com/sarink/react-file-drop/blob/master/src/FileDrop/tsconfig.json#L6

But the output contains ES6 code. I suspect this is the problem:

https://stackoverflow.com/questions/41993811/understanding-target-and-module-in-tsconfig

For compatibility we would need to use require() unfortunately (though TS should just be able to generate this for you).

**Comment by stevebaxter** [comment]
TBH this isn't an urgent issue. We moved back to the much more complex react-dropzone and we've then had to solve a load of other issues (we ended up moving from Webpack to Rollup). It's possible this isn't an issue now!
