### ISSUE TITLE
Why is prop-types a dependency?

### ISSUE THREAD

**Issue by borisyordanov** [sarink/react-file-drop#40]
Considering you already use TS it seems obsolete to me.
The main value proposition of your lib IMO is that it has fewer dependencies and a smaller bundle size compared to `react-dropzone`.

Removing all dependencies and reducing the bundle size further will sweeten the deal even further.

**Comment by sarink** [comment]
Hey @borisyordanov, this is a dependency for those that want to use this library without typescript. Because `prop-types` are dev dependencies only and will be stripped out in any production build, it is harmless! :)
