### ISSUE TITLE
Cannot Use In Typescript App

### ISSUE THREAD

**Issue by kevineaton** [sarink/react-file-drop#41]
I was trying to use this library in a create-react-app application using the Typescript scripts. However, When I insert the component as such:

`                 <FileDrop onDrop={this.handleDrop}>
                    <div className="file-drop-target">
                      Drop the file you would like to upload here
                    </div>
                  </FileDrop>
`

I get the following error:
`JSX element class does not support attributes because it does not have a 'props' property.ts(2607)
(JSX attribute) onDrop: (files: any, event: any) => void`

**Comment by sarink** [comment]
Hey @kevineaton, I've never seen this error, can you paste some more code? I think it's something specific with your setup. Have you tried using the demo code?

**Comment by kevineaton** [comment]
Hello! Unfortunately I dropped the library and used Dropzone. It likely has something to do with the Tyepscript typings, perhaps being out of sync. I can try to recreate it over the weekend.

**Comment by thunderkid** [comment]
I'm getting the same problem.

I've tried various forms of the `import` statement, eg
```import { FileDrop } ...```
```import * as FileDrop ...```
etc.

but can't get it to work. I think it's related to the type of module imports being used. eg in your demo code your `tsconfig.json` has `allowSyntheticDefaultImports: true`. My own `tsconfig.json` is this:
```
{
    "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "core/*": ["../../common/ts/*"],
            "createdByBuild/*": ["out/createdByBuild/*"]
        },
        "outDir": "out/built/",
        "module": "esnext",
        "target": "es5",
        "lib": [
            "dom",
            "dom.iterable",
            "es5",
            "es2015",
            "es2016"
        ],
        "sourceMap": true,
        "allowJs": true,
        "jsx": "react",
        "moduleResolution": "node",
        "rootDir": "../..",
        "noEmitOnError": true,
        "noImplicitReturns": false,
        "noImplicitThis": true,
        "noImplicitAny": false,
        "strictNullChecks": true,
        "strictPropertyInitialization": true,
        "noUnusedLocals": false,
        "experimentalDecorators": true
    }
}
```

I've actually solved the problem in my own situation simply by cutting and pasting your `FileDrop` class into my own codebase rather than trying to import from the library at all. It's now working fine for me, but this obviously isn't the right long-term solution.

**Comment by sarink** [comment]
@kevineaton @thunderkid would #42 fix this? `0.2.8` has been released, if you wouldn't mind giving it a shot!

**Comment by jsargeim** [comment]
@sarink so I have 0.2.8 and typescript is giving me an error. I'm using a program that will compile with nominal typescript errors, so it is working - but has an error.

![Picture](https://user-images.githubusercontent.com/48102198/55499653-bf8b9f80-5603-11e9-9f3d-60fc8923b9e4.png)

```
import * as React from 'react';

import FileDrop from 'react-file-drop';

export class Demo extends React.Component {

  handleDrop = (files: FileList, event: React.DragEvent<HTMLDivElement>) => {
    console.log('handleDrop!', files, event);
  }

  render() {
    const styles = { border: '1px solid black', width: 600, color: 'black', padding: 20 };
    return (
      <div id="react-file-drop-demo" style={styles}>
        <FileDrop onDrop={this.handleDrop}>
          Drop some files here!
        </FileDrop>
      </div>
    );
  }
}

**Comment by sarink** [comment]
Is anyone encountering this issue willing to push up a demo repo somewhere that it's reproducible? I'll play around with it

**Comment by jsargeim** [comment]
@sarink I'll do it tonight, so in about 5-6 hours.

**Comment by thunderkid** [comment]
@sarink: I've tried `0.2.8` with the variants:
```
import FileDrop from  'react-file-drop'; 
import { FileDrop } from  'react-file-drop'; 
import * as FileDrop from  'react-file-drop'; 
```
and the same `tsconfig.json` I showed above. All give typescript compilation errors.

**Comment by jsargeim** [comment]
@sarink so i can't reproduce the error, but this error is now popping up. I'm still learning typescript, so feel free to correct any mistakes I might've made. Here's the repo.

https://github.com/jsargeim/react-file-drop-demo

```Type '(files: FileList, event: DragEvent<HTMLDivElement>) => FileList' is not assignable to type '(files: FileList | null, event: DragEvent<HTMLDivElement>) => any'.
  Types of parameters 'files' and 'files' are incompatible.
    Type 'FileList | null' is not assignable to type 'FileList'.
      Type 'null' is not assignable to type 'FileList'.ts(2322)

**Comment by ezekg** [comment]
I was still having this issue with v3. After digging around, it's because this library (in the compiled `FileDrop.d.ts`) declares typings from `@types/prop-types`, `@types/react`, and `@types/react-dom`, but you've defined these as dev dependencies, so the typings end up being invalid. To resolve this, I added those packages as dev dependencies to my own project. Perhaps these should be declared as dependencies, not dev dependencies.

```
yarn add @types/prop-types @types/react @types/react-dom --dev
```
