### ISSUE TITLE
Include other drop types?

### ISSUE THREAD

**Issue by thunderkid** [sarink/react-file-drop#43]
This is a feature suggestion.
What do you think about broadening the library so that it also allows dropping images or text directly? ie allow an image to be dragged from another app without having to save it as a file first. It seems this would only add a small amount of code.

**Comment by sarink** [comment]
Although _file_ drop is in the name and it intentionally only allows files, if this is a small and clean code change, I am open to it. What were you imagining @thunderkid ?
