### ISSUE TITLE
Drag state does not canceled in IE

### ISSUE THREAD

**Issue by PFight** [sarink/react-file-drop#48]
IE has a bug: https://stackoverflow.com/questions/40680879/dragleave-is-not-firing-in-ie
See for example https://jsfiddle.net/1m0gbL4d/4/

Due to this bug library does not work correctly in IE. If you begin dragging file, and then move file away - drag state preserves, frameDragCounter still more the zero, and next drag does not begin. 

I have made hotfix in local copy of library installation:
![image](https://user-images.githubusercontent.com/198847/69542999-b047d080-0f9d-11ea-8418-206b358449cb.png)

This fix not ideal - it only cover case, when you cancel drag, then move a mouse over page, then begin another drag. Do not know, how to fix whole case.

**Comment by sarink** [comment]
Is this still an issue today? Please reopen if so.

**Comment by PFight** [comment]
It's repro in oficial demo https://sarink.github.io/react-file-drop/
Here state after I started dragging file, then moved file away and canceled drag:
![image](https://user-images.githubusercontent.com/198847/123076294-ad36ef80-d421-11eb-9091-06f2fa049205.png)

![image](https://user-images.githubusercontent.com/198847/123076385-c2ac1980-d421-11eb-9700-d5fdb7cb3605.png)
