### ISSUE TITLE
Using frame prop

### ISSUE THREAD

**Issue by Falsen** [sarink/react-file-drop#52]
Hello I am trying to use the "frame" prop without any success.

Frame must be of the type HTMLDocument but how can I generate an HTMLDocument inside render()? I was going to use document.getElementById, but I quickly realized that isn't an option since the HTML isn't yet rendered on the page in the render() function. So how can I create an HTMLElement inside the render function itself?

Could you please provide an example

**Comment by sarink** [comment]
@Falsen I don't understand your problem. You can pass a `frame` that is _any html element_ or, _the entire document_. Just create a div somewhere, and pass that as the `frame` prop.

**Comment by namti** [comment]
Seems that the `frame` type excludes `HTMLElement`. It only accept `HTMLDocument` type.

```tsx
<FileDrop
  frame={ document.querySelector<HTMLDivElement>('.resource-manager-file-area') ?? undefined }
  onDrop={ files => onUploadFiles(files) }
>
  <span>Drop files to upload</span>
</FileDrop>
```

**Type Error**
```typescript
Type 'HTMLDivElement | undefined' is not assignable to type 'HTMLDocument | undefined'.
  Type 'HTMLDivElement' is missing the following properties from type 'HTMLDocument': URL, alinkColor, all, anchors, and 96 more.
```
`node_modules/react-file-drop/FileDrop.d.ts`
```typescript
10  frame?: Exclude<HTMLElementTagNameMap[keyof HTMLElementTagNameMap], HTMLElement> | HTMLDocument;
```
