### ISSUE TITLE
Does react-file-drop support the "accept" attribute?

### ISSUE THREAD

**Issue by danmandel** [sarink/react-file-drop#59]
Trying to get this to only allow csv/xlxs files and I couldn't find anything about the [accept attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/accept) in the docs. Is it supported?

**Comment by sarink** [comment]
Hey @danmandel , the `accept` attribute only applies to `<input>` elements, react-file-drop just (renders a div)[https://github.com/sarink/react-file-drop/blob/master/file-drop/src/FileDrop.tsx#L208].

You should be able to handle this yourself by writing your own `onDrop` function, perhaps something like
```
  <FileDrop
    onDrop={(files) => {
      const allowedExts = ['.csv', '.xlsx'];
      const isFileAllowed = (file) => allowedExts.includes(file.split('.')[1]);
      const allowedFiles = files.filter(isFileAllowed);
      const disallowedFiles = files.filter(f => !isFileAllowed(f));
      // do something with these files
    })
/>
```
