### ISSUE TITLE
How to add file clicker?

### ISSUE THREAD

**Issue by rowanG077** [sarink/react-file-drop#66]
This component is exactly what I need. But most of these components you can see online still have normal button to upload a file instead of only drag and drop. I don't see a way to do this with this component. Or are we supposed to just add another file element  with the file dropper if we want this behaviour?

**Comment by sarink** [comment]
You don't need any library to do this, it's all straightforward built in native behavior. There is however an outstanding PR to introduce this, I haven't decided if it should be merged in or just documented yet though. Take a look at the code: https://github.com/sarink/react-file-drop/pull/62

**Comment by nsjithin** [comment]
I think it will be very much needed requirement. Is there any way we can achieve without this PR? outside of the library? I can add a `clickHandler` for the parent, but not sure about the significance `this.resetDragging();` line in PR.

**Comment by sarink** [comment]
Resolved by #62
