### ISSUE TITLE
In Firefox the drop area will not disappear after drag leave

### ISSUE THREAD

**Issue by Joe-Ying** [sarink/react-file-drop#8]
Seems like there's some issue about the drag leave event handling.

**Comment by Joe-Ying** [comment]
Reproducible for the demo in Firefox:
http://sarink.github.io/react-file-drop/demo/

**Comment by sarink** [comment]
I'm on OSX, Firefox version 44.0.2, and it appers to work fine? Can you describe the problem and your environment in more detail?

**Comment by Joe-Ying** [comment]
The case is when you dragging a file enter the window, the drop area appears; then you hold it and move it out of the window, the drop area doesn't disappear. It should disappear as expected.
This can be reproduced in OSX Firefox 44.0.2 and 45.

**Comment by sarink** [comment]
Sorry, been really busy! I've finally had some time to investigate this...

Here's the reason: https://bugzilla.mozilla.org/show_bug.cgi?id=656164
Here's a possible workaround: http://stackoverflow.com/questions/10253663/how-to-detect-the-dragleave-event-in-firefox-when-dragging-outside-the-window

The fix won't be that difficult, it will basically be reverse-engineering that SO answer but without jquery. It's kind of hacky and not very efficient, but after understanding what causes the problem, I can't think of a better way myself.

Hopefully I can get this patched up soon. In the meantime, if anyone else feels like tackling it, go ahead and submit a PR! 😀

**Comment by ErwinLee10** [comment]
I am having this issue as well, anyone can guide me on this issue?

Basically the onFrameDragEnter will not be triggered again after dragging the file out and enter again.
