### ISSUE TITLE
Filter js Files

### ISSUE THREAD

**Issue by renanmachad** [sarink/react-file-drop#82]
Hello, if a client drop a js file this stop my server in nodejs, how i can filter this? Using this library?

**Comment by sarink** [comment]
Hello, you should be able to handle that easily in the `onDrop` function, something like this should work:
```
onDrop={(files, event) => {
  const jsFiles = files.filter(file => file.name.endsWith('.js'));
  console.log(jsFiles);
});
```

**Comment by renanmachad** [comment]
Hello, oh my god i don´t have thought about it.Thanks so much;
