### ISSUE TITLE
Props Warning

### ISSUE THREAD

**Issue by proffnick** [sarink/react-file-drop#83]
I followed proper installation guides but receive this warning in console:

index.js:1 
        
       Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state

Please update the following components: FileDrop

This is my code: 
`<FileDrop onDrop={processDroppedFiles} onTargetClick={onTargetClick} className="kpFilesDrag position-relative p-5 rounded-3"/>`

How do I fix it?

**Comment by RedBlood639** [comment]
Hi, How are you ?
Now I am using 'react-file-drop' module, but I had same error with you. So if you solved this problem, please let me know.
Thank you
![image](https://user-images.githubusercontent.com/72724141/144241412-6a4b430d-7ec1-42d8-90f4-20cfb012a4ca.png)

**Comment by proffnick** [comment]
I have not been able to resolve the issue. I am guessing they will have to
update the package to resolve the issue, however, if I am able to find a
way around it, I will get back. For the meantime you may like to remove
react from strict mode.
*Nicholas Mberev*
*Director*: Amtel WEb Design & Graphics Technology.
Websites Design, Graphics Design, Search Engines Optimization,
Web Portal Creation, Web Hosting, Domain Registration, Bulksms etc. :
*Contact*:    *+2348133191426*
*Websites: *www.amtelwebsitedesigner.com
*Emails*:      ***@***.*** ***@***.***> *
                 ***@***.*** ***@***.***>

**Comment by sarink** [comment]
Updating this library to use hooks instead of lifecycle methods is on my to-do list. Until then, you'll have to disable strict mode or ignore these warnings :-/
