### ISSUE TITLE
Using UNSAFE_componentWillReceiveProps in strict mode

### ISSUE THREAD

**Issue by Birkenpapier** [sarink/react-file-drop#85]
Using the component inside an parent component will lead to this error: 

![grafik](https://user-images.githubusercontent.com/11006393/148134119-72d9919c-329f-4f62-a709-5d0736b9165f.png)

What can be done about this?

**Comment by sarink** [comment]
Dup of https://github.com/sarink/react-file-drop/issues/83

This lib needs to be rewritten with hooks and stop using the deprecated lifecycle methods. It may be awhile until I get around to that. Functionally speaking, everything works. Unfortunately, the only solution to this warning is to disable strict mode for now.
