### ISSUE TITLE
UNSAFE Warning

### ISSUE THREAD

**Issue by davidbilling** [sarink/react-file-drop#86]
Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state

Please update the following components: FileDrop

**Comment by sarink** [comment]
Dup of https://github.com/sarink/react-file-drop/issues/85
