### ISSUE TITLE
_handleDragOver works incorrectly in Chrome on Linux

### ISSUE THREAD

**Issue by scriptguru** [sarink/react-file-drop#9]
It doesn't work in both my current app and in the demo http://sarink.github.io/react-file-drop/demo/

Here is the code from FileDrop.js

```
        _handleDragOver: function (event) {
            event.preventDefault();
            event.stopPropagation();
            event.dataTransfer.dropEffect = this.props.dropEffect;

            // set active drag state only when file is dragged into
            // (in mozilla when file is dragged effect is "uninitialized")
            var effectAllowed = event.dataTransfer.effectAllowed;
            if (effectAllowed === "all" || effectAllowed === "uninitialized") {
                this.setState({draggingOverTarget: true});
            }

            if (this.props.onDragOver) this.props.onDragOver(event);
        }
```

To me it looks like the problem is that condition `effectAllowed === "all" || effectAllowed === "uninitialized"` is never true because effectsAllowed === "copy" in Chrome on Linux.

I could be wrong, I haven't tested it very carefully, but to me this looks like the cause of the issue.

**Comment by sarink** [comment]
If this still occurs in v2, please reopen
