### ISSUE TITLE
When using in next js. Have to restart every time code is changed in `Demo.js`

### ISSUE THREAD

**Issue by ZeeshanAhmadKhalil** [sarink/react-file-drop#97]
I installed `react-file-drop` through:

> yarn add react-file-drop

Into my next js project. And using the code from the [demo](https://sarink.github.io/react-file-drop/) example. Now after changing any thing in `Demo.js` i have to restart my next.js app in order to apply those changes.

**Comment by ZeeshanAhmadKhalil** [comment]
Currently using `react-dropzone`

**Comment by sarink** [comment]
This is something to do with your app's build configuration, there's nothing in `react-file-drop` that would cause this. As you can see from running the demo app in this repo, hot module replacement works fine with the right config.
